language: go

go: 
 - 1.11

go_import_path: github.com/harbur/captain

services:
  - docker

before_install:
  - go get github.com/Masterminds/glide
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - glide install
  - go get

install: true
script: true

#script:
# - go test -v -covermode=count -coverprofile=coverage.out
#  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
