language: go
sudo: false
matrix:
  include:
    - go: 1.11
  allow_failures:
    - go: tip

go_import_path: github.com/harbur/captain

before_install:
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -t -v ./...
#  - diff -u <(echo -n) <(gofmt -d .)
#   - go vet ./...
#   - go test -v -race ./...
  # Only build binaries from the latest Go release.
  - gox -os="linux" -arch="amd64" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $api_key
  file:
  - captain_linux_amd64
  on:
    repo: yusofleet/captain
    tags: true
